// Ceremli wedding party + gallery editor. Media is resized in-browser then persisted to the wedding account.
(function(){
 const style=document.createElement('style');style.textContent=`
 [data-party-list],[data-gallery-list],.studio-controls,.form-card{min-width:0;max-width:100%}
 .media-person{display:grid;grid-template-columns:88px minmax(0,1fr) 36px;gap:14px;align-items:start;padding:14px 0;border-bottom:1px solid var(--line);min-width:0}
 .media-person img{width:88px!important;height:110px!important;max-width:88px!important;object-fit:cover!important;object-position:center!important;border-radius:14px;display:block}
 .media-person>div{min-width:0}.media-person strong,.media-person small,.media-person p{display:block;overflow-wrap:anywhere}.media-person small{color:var(--muted);margin-top:3px}.media-person p{margin:7px 0 0}
 .party-group-title{font:700 18px Georgia,serif;margin:22px 0 10px}.party-preview-group+.party-preview-group{margin-top:26px}.party-preview-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px}.party-preview-card{min-width:0;overflow:hidden}.party-preview-card img{display:block;width:100%!important;height:150px!important;max-width:100%!important;object-fit:cover!important;object-position:center!important;border-radius:14px}.party-preview-card strong,.party-preview-card small,.party-preview-card p{display:block}.party-preview-card small{color:var(--muted);margin-top:3px}.party-preview-card p{margin:6px 0 0}
 .gallery-edit-grid,.gallery-preview-grid{display:grid!important;grid-template-columns:repeat(3,minmax(0,1fr))!important;gap:10px!important;width:100%!important}.gallery-edit-item{position:relative;min-width:0;overflow:hidden;border-radius:14px;aspect-ratio:1/1}.gallery-edit-item img,.gallery-preview-grid>img{display:block!important;width:100%!important;height:150px!important;max-width:100%!important;object-fit:cover!important;object-position:center!important;border-radius:14px!important}.gallery-edit-item img{height:100%!important}.gallery-edit-item .icon-btn{position:absolute;top:4px;right:4px;background:rgba(255,255,255,.9);border-radius:50%;width:32px;height:32px;line-height:1}
 [data-party-form] .btn{min-height:46px;color:var(--ink);background:#fff;border:1px solid var(--line);white-space:normal;text-align:center}.party-group-field{display:block;margin-top:12px}.party-group-field select{margin-top:6px}
 @media(max-width:900px){html,body{max-width:100%;overflow-x:hidden}.app-content.studio-layout{display:flex!important;flex-direction:column!important;width:100%!important;max-width:100%!important;padding:16px!important;gap:18px!important;overflow:visible!important}.studio-controls{display:grid!important;grid-template-columns:1fr!important;gap:16px!important;order:1!important;width:100%!important;max-width:100%!important;min-width:0!important;visibility:visible!important;opacity:1!important}.studio-preview-wrap{position:static!important;order:2!important;width:100%!important;max-width:100%!important;min-width:0!important}.form-card{display:block!important;width:100%!important;max-width:100%!important;min-width:0!important;overflow:hidden!important}.site-preview{width:100%!important;max-width:100%!important;min-width:0!important;overflow:hidden!important}.builder-topbar{height:auto!important;min-height:78px!important;padding:18px!important;gap:14px!important;align-items:flex-start!important;flex-wrap:wrap!important}.builder-actions{width:100%!important;display:flex!important;gap:10px!important;flex-wrap:wrap!important}}
 @media(max-width:560px){.media-person{grid-template-columns:72px minmax(0,1fr) 32px;gap:10px}.media-person img{width:72px!important;height:90px!important;max-width:72px!important}.party-preview-grid{grid-template-columns:1fr 1fr}.party-preview-card img{height:120px!important}.gallery-edit-grid,.gallery-preview-grid{grid-template-columns:repeat(2,minmax(0,1fr))!important}.gallery-preview-grid>img{height:120px!important}[data-party-form] .btn{width:100%}.theme-grid,.toggle-list{grid-template-columns:1fr!important}}
 `;document.head.appendChild(style);
 const plan=()=>ME?.plan||'free';
 const limits=()=>plan()==='ultimate'?{party:40,gallery:50}:plan()==='premium'?{party:20,gallery:24}:{party:8,gallery:8};
 const groupOf=p=>{if(p.group)return p.group;const r=String(p.role||'').toLowerCase();if(/groom|best man/.test(r))return'groomsmen';if(/bride|maid of honour|maid of honor|matron/.test(r))return'bridesmaids';return'other'};
 const groupLabel=g=>g==='bridesmaids'?'Bridesmaids':g==='groomsmen'?'Groomsmen':'Family & others';
 const compress=file=>new Promise((resolve,reject)=>{const img=new Image(),url=URL.createObjectURL(file);img.onload=()=>{try{const max=1200,scale=Math.min(1,max/Math.max(img.width,img.height)),c=document.createElement('canvas');c.width=Math.max(1,Math.round(img.width*scale));c.height=Math.max(1,Math.round(img.height*scale));c.getContext('2d').drawImage(img,0,0,c.width,c.height);const data=c.toDataURL('image/jpeg',.82);URL.revokeObjectURL(url);resolve(data)}catch(e){reject(e)}};img.onerror=()=>{URL.revokeObjectURL(url);reject(new Error('Could not read image'))};img.src=url});
 async function start(){
  if(document.body?.dataset?.page!=='builder')return;
  const form=document.querySelector('[data-party-form]');
  if(form&&!form.elements.group){const role=form.elements.role;const wrap=document.createElement('label');wrap.className='party-group-field';wrap.innerHTML='Group<select class="input" name="group"><option value="bridesmaids">Bridesmaids</option><option value="groomsmen">Groomsmen</option><option value="other">Family & others</option></select>';role.closest('label')?.after(wrap)}
  if(plan()==='free')document.querySelectorAll('.theme-choice[data-theme="romantic"],.theme-choice[data-theme="modern"]').forEach(b=>b.addEventListener('click',e=>{e.preventDefault();e.stopImmediatePropagation();if(confirm('This design is included with Ceremli Premium. View plans?'))location.href='/pricing.html'},true));
  let s={party:[],gallery:[]};try{s=await api('/api/wedding/media')}catch(e){console.error(e);toast('Could not load wedding photos')}s.party=s.party||[];s.gallery=s.gallery||[];
  const party=document.querySelector('[data-party-list]'),gallery=document.querySelector('[data-gallery-list]');const persist=async()=>{await api('/api/wedding/media',{method:'PUT',body:JSON.stringify(s)})};
  const card=p=>`<div class="party-preview-card">${p.photo?`<img src="${p.photo}" alt="${esc(p.name)}">`:''}<strong>${esc(p.name)}</strong><small>${esc(p.role)}</small><p>${esc(p.bio||'')}</p></div>`;
  const grouped=rows=>['bridesmaids','groomsmen','other'].map(g=>{const items=rows.filter(p=>groupOf(p)===g);return items.length?`<div class="party-preview-group"><div class="party-group-title">${groupLabel(g)}</div><div class="party-preview-grid">${items.map(card).join('')}</div></div>`:''}).join('');
  const renderPreview=()=>{const pp=document.querySelector('[data-preview-party]'),pg=document.querySelector('[data-preview-gallery]');if(pp){pp.style.display=s.party.length?'block':'none';pp.querySelector('[data-preview-party-grid]').innerHTML=grouped(s.party)}if(pg){pg.style.display=s.gallery.length?'block':'none';pg.querySelector('[data-preview-gallery-grid]').innerHTML=s.gallery.map(x=>`<img src="${x.src}" alt="Wedding photo">`).join('')}};
  const draw=()=>{party.innerHTML=s.party.length?s.party.map((p,i)=>`<div class="media-person">${p.photo?`<img src="${p.photo}" alt="">`:''}<div><strong>${esc(p.name)}</strong><small>${esc(groupLabel(groupOf(p)))} · ${esc(p.role)}</small><p>${esc(p.bio||'')}</p></div><button class="icon-btn" data-party-delete="${i}" type="button">×</button></div>`).join(''):'<p class="muted">No wedding party members added yet.</p>';gallery.innerHTML=s.gallery.length?s.gallery.map((x,i)=>`<div class="gallery-edit-item"><img src="${x.src}" alt=""><button class="icon-btn" data-gallery-delete="${i}" type="button">×</button></div>`).join(''):'<p class="muted">No gallery photos yet.</p>';renderPreview()};
  form.onsubmit=async e=>{e.preventDefault();const max=limits().party;if(s.party.length>=max)return toast(`Your ${plan()} plan includes up to ${max} wedding party members`);const f=e.currentTarget,d=Object.fromEntries(new FormData(f)),photo=f.elements.photo.files[0],btn=f.querySelector('button[type=submit]');btn.disabled=true;btn.textContent='Saving…';try{if(photo)d.photo=await compress(photo);s.party.push({name:String(d.name||'').trim(),role:String(d.role||'').trim(),group:String(d.group||'other'),bio:String(d.bio||'').trim(),photo:d.photo||''});await persist();f.reset();draw();toast('Wedding party member saved')}catch(x){s.party.pop();toast(x.message||'Could not save photo')}finally{btn.disabled=false;btn.textContent='Add wedding party member'}};
  document.querySelector('[data-gallery-input]').onchange=async e=>{const room=Math.max(0,limits().gallery-s.gallery.length),files=[...e.target.files].slice(0,room);if(!files.length){toast(`Your ${plan()} plan gallery limit is ${limits().gallery} photos`);e.target.value='';return}toast('Preparing photos…');const startCount=s.gallery.length;try{for(const f of files)s.gallery.push({src:await compress(f)});await persist();draw();toast(`${files.length} photo${files.length===1?'':'s'} saved`)}catch(x){s.gallery=s.gallery.slice(0,startCount);draw();toast(x.message||'Could not save photos')}e.target.value=''};
  document.addEventListener('click',async e=>{let b=e.target.closest('[data-party-delete]');if(b){const i=+b.dataset.partyDelete,old=s.party.splice(i,1)[0];draw();try{await persist();toast('Wedding party member removed')}catch{s.party.splice(i,0,old);draw();toast('Could not remove member')}return}b=e.target.closest('[data-gallery-delete]');if(b){const i=+b.dataset.galleryDelete,old=s.gallery.splice(i,1)[0];draw();try{await persist();toast('Photo removed')}catch{s.gallery.splice(i,0,old);draw();toast('Could not remove photo')}}});draw();
 }
 if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(start,80));else setTimeout(start,80);
})();